name: Bug Report (EN)
description: Create a report to help us improve
title: "[Bug]: (fill in)"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have verified that this issue is not a duplicate. (Search
            [here](https://github.com/bam1279/share-switch/issues)  to find
            out.)
          required: true
        - label: I have verified that other extensions are not causing the issue.
          required: true
        - label: I have verified that the issue still occurs after upgrading to the latest
            version.
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      value: |
        <details>
        <summary>Screenshot(s)</summary>

        <!-- Drag-and-drop screenshot here -->
        <!-- ⬇️  ⬇️  ⬇️ -->


        <!-- ⬆️  ⬆️  ⬆️ -->

        </details>
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Desktop (please complete the following information):"
      description: |
        examples:
          - **OS**: Windows 11
          - **Browser**: Chrome
          - **Browser Version**: 123
      value: |
        - OS:
        - Browser:
        - Browser Version:
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Do you want to address this bug yourself?
      options:
        - label: Yes, I will patch the bug myself and send a pull request
          required: false
