---
name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: (fill in)"
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have verified that this issue is not a duplicate. (Search
            [here](https://github.com/bam1279/share-switch/issues)  to find
            out.)
          required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        A clear and concise description of what the problem is.
        Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or
        features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Do you want to implement this feature yourself?
      options:
        - label: Yes, I will implement this by myself and send a pull request
          required: false
